### ISSUE TITLE
elm-parts has functions in the Msg type

### ISSUE THREAD

**Issue by CIB** [MichaelCombs28/elm-mdl#1]
Confer https://github.com/debois/elm-parts#drawbacks

Basically, because of how elm-parts is designed, the new debugging features just don't work at all when using elm-mdl. This makes elm-mdl pretty much pointless for me.

![screenshot_2016-11-22_21-57-58](https://cloud.githubusercontent.com/assets/902211/20541741/c6bb11c0-b0fe-11e6-9e8e-3b5138db9be7.png)

**Comment by MichaelCombs28** [comment]
I'm in the planning stages of building a Material Design library for Elm using the sortable table concepts and style.

Unfortunately your issue is a non-issue since the drawbacks have not only been described on the README, but as a problem of the library this framework is built on.

When I begin the project I'll have a trello board ready and will be looking for contributors to help out.
